project:
  type: book
  output-dir: docs
  
book:
  title: "\\textbf{Structure-Based Discovery of Putative Novel Deep-Sea Hydrothermal Chitinases}"
  date: today
  date-format: "MMMM YYYY"
  chapters:
    - index.qmd
#    - acknowledgements.qmd         # uncomment this line to see acknowledgements in html (will appear twice in pfd)
    - 0-abstract.qmd
    - 1-introduction.qmd
    - 2-methods.qmd
    - 3-results.qmd
    - 4-discussion.qmd
    - 5-conclusions.qmd
    - references.qmd
  appendices:
    - app1-resources.qmd
    - app2-tools.qmd

bibliography: references.bib

execute:
  echo: true # change to false to hide code

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrbook
    keep-tex: true 
    toc: false
    papersize: a4
    header-includes: |
      \usepackage{titling}
      \usepackage{lmodern}
      \usepackage{graphicx}
      \usepackage{geometry}
      \usepackage{setspace}
      \onehalfspacing
      \geometry{margin=2.5cm}
      \setlength{\droptitle}{-2cm}  % Adjust this value to move the title up
      \pretitle{
        \begin{center}
        \vspace*{-2cm}  % Move the title up
        \huge\bfseries  % Make the title bold and large
      }
      \posttitle{
        \par
        \end{center}
        \vspace*{3cm}  % Adjust this value to control the space after the title
      }
      \preauthor{
        \begin{center}
        \vspace{-2cm}  % Adjust this value to move the picture up
        \includegraphics[width=4in,height=3in]{figures/IMG_20210719_134928644.jpg}\\ % Cover figure
        \vspace{0.5cm}  % Adjust this value to control the space between the picture and the author
        \Large\bfseries Guro Ødegårdstuen\\
        \vspace{0.2cm}  
        \end{center}
      }
        \postauthor{
        \begin{center}
        {\large{Supervisors:}}\\
        \large
        Researcher \textbf{Runar Stokke}\\
        Postdoc \textbf{Hasan Arsın}\\
        Professor \textbf{Ida Helene Steen}\\
        \vspace{1.5cm} 
        \includegraphics[width=1.7in,height=1.7in]{figures/UiB-emblem500px_gray.png}\\
        \end{center}
      } 
      \predate{
        \begin{center}
        \large
        Master of Science in Biology | Microbiology\\  % Degree
        Department of Biological Sciences\\            % Department
        University of Bergen\\                         % University 
      }
       \postdate{
       \end{center}
       \newpage
       \mbox{}
       \vfill
       Cover page:\\
       \emph{Beckwithia glacialis} on Snøhetta.
      }
editor: visual

